### ISSUE TITLE
error: dependency graph is unresolvable

### ISSUE THREAD

**Issue by fabiopdm** [uraimo/SG90Servo.swift#1]
First of all, thanks for your package! 

I'm trying to compile on a Raspberry Pi 3 B+, with Raspbian OS and Swift 5.0.1. When I build I received this error: 

> Updating https://github.com/uraimo/SG90Servo.swift.git
error: dependency graph is unresolvable; found these conflicting requirements:
Dependencies: 
    https://github.com/uraimo/SG90Servo.swift.git @ 2.0.0..<3.0.0

Maybe is something with the version reference of the SwiftyGPIO, or other problem. I'm a beginner on Swift and I have no clue where this problem can be. I'll appreciate any help.

Best regards.

**Comment by uraimo** [comment]
Hi! 
I'm back from vacation, I'm in the process of updating all the driver libraries that depend on SwiftyGPIO to 4.x and this should solve this issue too. Check back in a few hours and you should see a 3.0.0 release for SG90Servo.swift.

**Comment by uraimo** [comment]
Ok, solved with 3.0.2, check out `Examples/Raspi2` for an example of 4.0-style Package.swift.
